version: "3.8"
name: titanium-simple

services:

  #Nacos
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    env_file:
      - ../env/nacos-standalone.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy

  #Mysal
  mysql:
    container_name: mysql-8.0.30
    image: titanium/mysql:8.0.30
    build:
      context: .
      dockerfile: ../images/mysql/mysql-8.Dockerfile
    env_file:
      - ../env/mysql.env
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  #Redis
  redis:
    container_name: redis-7.4
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"
    volumes:
      - ~/redis_data/data:~/software/redis/data
      - ~/redis_data/conf/redis.conf:../init/redis/redis-standalone.conf