version: "3.8"
name: titanium-cloud-alibaba

services:

  #Nacos localhost:8848/nacos/ nacos/marco520
  nacos:
    networks:
      - default
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    env_file:
      - ../env/nacos-standalone.env
    volumes:
      - ../data/standalone-logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/actuator/health"]  # 使用curl检查Nacos的健康状态
      interval: 10s  # 每30秒检查一次
      timeout: 20s  # 检查的超时时间
      retries: 3  # 如果连续3次检查失败，则认为容器不健康
#      start_period: 20s  # 容器启动后，等待40秒再进行健康检查（可选）

  #seata http://localhost:7091/ marco/marco520
  seata-server:
    networks:
      - default
    container_name: seata
    image: seataio/seata-server:${SEATA_VERSION}
    ports:
      - "7091:7091"
      - "8091:8091"
    env_file:
      - ../env/seata.env
    environment:
      - TZ=Asia/Shanghai #设置时区
    volumes:
      # 假设我们通过docker cp命令把资源文件拷贝到相对路径`./seata-server/resources`中
      # 如有问题，请阅读上面的[注意事项]以及[使用自定义配置文件]
      - "../init/seata/seata-application.yml:/seata-server/resources/application.yml"
    depends_on:
      mysql:
        condition: service_healthy
      nacos:
        condition: service_healthy

  #Mysal 3306 root/marco520
  mysql:
    networks:
      - default
    container_name: mysql-8.0.30
    image: titanium/mysql:8.0.30
    build:
      context: .
      dockerfile: ../images/mysql/mysql-8.Dockerfile
    env_file:
      - ../env/mysql.env
    volumes:
      - ../data/mysql:/var/lib/mysql
      - ../init/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  #Redis
  redis:
    networks:
      - default
    container_name: redis-7.4
    image: redis:${REDIS_VERSION}
    ports:
      - "6379:6379"
    volumes:
      - ~/software/redis/data:/data
      - ../init/redis/redis-standalone.conf:/etc/redis/redis.conf

  # Elasticsearch (used by SkyWalking for storage)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - TZ=Asia/Shanghai #设置时区
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file:
      - ../env/elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ../data/elasticsearch:/usr/share/elasticsearch/data
#      - ../init/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  #skywalking
  skywalking-oap:
    networks:
      - default
    container_name: skywalking-oap
    image: apache/skywalking-oap-server:${SKYWALKING_VERSION}
    environment:
      - TZ=Asia/Shanghai #设置时区
    env_file:
      - ../env/skywalking-opa.env
    ports:
      - "11800:11800" # gRPC for agents
      - "12800:12800" # RESTful backend for UI
    volumes:
      - ~/software/skywalking-oap/data:/skywalking/data
    depends_on:
      - elasticsearch
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:12800/healthcheck || exit 1" ]
      interval: 10s # 每 10 秒检查一次
      timeout: 5s   # 健康检查超时时间为 5 秒
      retries: 3    # 如果连续 3 次失败，则认为容器不健康
      start_period: 30s # 容器启动后等待 30 秒再开始健康检查

  #https://hub.docker.com/r/apache/skywalking-ui
  skywalking-ui:
    networks:
      - default
    container_name: skywalking-ui
    image: apache/skywalking-ui:${SKYWALKING_VERSION}
    environment:
      - TZ=Asia/Shanghai #设置时区
    env_file:
      - ../env/skywalking-ui.env
    ports:
      - "8090:8080"
    depends_on:
      - skywalking-oap



networks:
  host:
    driver: host
  bridge:
    driver: bridge
  overlay:
    driver: overlay
  macvlan:
    driver: macvlan
  ipvlan:
    driver: ipvlan
  default:
    driver: bridge
